version: "3.8"

services:
  database:
    image: postgres:12
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2.1-buster
    ports:
      - "6379:6379"
  
  app:
    build: .
    env_file:
      - .env
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    depends_on:
      - database

  celery_worker:
    build: .
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    command: celery -A celery_worker.celery worker -l INFO -Q flight_search -c 100 -E
    depends_on:
      - redis

  flower:
    image: mher/flower
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    ports:
      - 5555:5555
    command: celery flower --port=5555
    depends_on:
      - redis
      - app
      - celery_worker
